# Generated by Django 4.0.4 on 2022-06-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('filepath', models.FileField(null=True, upload_to='file_uploads', verbose_name='')),
                ('uploaded', models.DateTimeField()),
                ('download_count', models.IntegerField()),
                ('api_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apiuser')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
            ],
        ),
    ]
